on:
  push:
    branches:
      - main
name: release-please
jobs:
  # 运行在 ubuntu-latest
  release-please:
    runs-on: ubuntu-latest

    steps:
      # 发布的检验
      - uses: google-github-actions/release-please-action@v3
        name: release-please
        id: release
        with:
          release-type: node
          package-name: "@iskl/eslint-plugin"
      # Checkout 仓库
      - uses: actions/checkout@v2
        name: Checkout
        if: ${{ steps.release.outputs.release_created }}
      # Install Node.js
      - uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      # 发布到npm
      - name: Deploy to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
